# Generated by Django 5.1.2 on 2024-10-17 08:06

import habits.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit', name='duration', field=models.PositiveIntegerField(
                help_text='Время на выполнение в секундах', validators=[
                    habits.validators.validate_duration]), ), migrations.AlterField(
            model_name='habit', name='frequency', field=models.PositiveIntegerField(
                default=1, help_text='Периодичность выполнения в днях', validators=[
                    habits.validators.validate_frequency]), ), ]
